name: Keep Repo Active
on:
  schedule:
    - cron: '0 0 * * 2'
  push:
    branches: [ "main" ]
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          date > date-built.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Date Built"
          git push
